cell(0,0,false,false,true,false).
cell(0,1,false,true,false,false).
cell(0,2,true,true,false,false).
cell(0,3,true,false,true,false).
cell(1,0,false,true,false,true).
cell(1,1,true,false,true,false).
cell(1,2,false,true,true,false).
cell(1,3,true,false,false,true).
cell(2,0,false,false,true,false).
cell(2,1,false,false,true,true).
cell(2,2,false,true,false,true).
cell(2,3,true,false,true,false).
cell(3,0,false,false,true,true).
cell(3,1,false,false,true,true).
cell(3,2,false,true,true,false).
cell(3,3,true,false,true,true).
cell(4,0,false,false,true,true).
cell(4,1,false,false,true,true).
cell(4,2,false,false,true,true).
cell(4,3,false,false,true,true).
cell(5,0,false,true,false,true).
cell(5,1,true,true,false,true).
cell(5,2,true,false,false,true).
cell(5,3,false,false,false,true).
hasPokimon(0,1).
hasPokimon(0,2).
hasPokimon(1,2).
hasPokimon(3,1).
hasPokimon(4,0).
hasPokimon(4,1).
playerLocation(s,5,0).
startPoint(5,0).
endPoint(1,3).
stepsToHatch(17).
